name: Run tests and upload coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: List files in node_modules/.bin
        run: ls -l node_modules/.bin

      - name: Check file permissions
        run: |
          ls -l node_modules/.bin/jest
          file node_modules/.bin/jest

      - name: Run tests
        run: npx jest --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
